[package]

name = "hello"
version = "0.0.1"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
repository = "https://github.com/Byron/depot"


[lib]
name = "mylib"
crate-type = ["rlib"]


[dev-dependencies]
rustc-serialize = "*"
chrono = "*"


